name: Publish to npm

on:
  release:
    types: [ created ]
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - id: check
        uses: EndBug/version-check@v2
        with:
          file-url: https://unpkg.com/quester-ui@latest/package.json
          static-checking: localIsNew
          
      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
    
      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci --legacy-peer-deps

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run build

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cp README.md dist/
          cp LICENSE dist/
          cd dist
          pwd
          npm publish
