name: Publish to npm

on:
  release:
    types: [ created ]
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_version.outputs.has_changed == 'true' }}

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Check if version has changed
        id: check_version
        run: echo ::set-output name=has_changed::$(git diff --name-only HEAD~1 HEAD | grep -c "package.json")
     

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish
